# -*- coding: utf-8 -*-

"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter
at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""

__author__ = 'yelongyu1024@gmail.com'


class Solution(object):
    def __init__(self, string_s, string_t):
        self.string_s = string_s
        self.string_t = string_t

    def find_the_difference(self):
        string_s = sorted(self.string_s)
        string_t = sorted(self.string_t)
        for char_s, char_t in zip(string_s, string_t):
            if char_s != char_t:
                return char_t
        return string_t[-1]


def main():
    solution = Solution('abcd', 'acbde')
    print solution.find_the_difference()


if __name__ == '__main__':
    main()
